name: base
channels:
dependencies:
   - setuptools
   - numpy
   - numba
   - scipy
   - matplotlib
   - astropy
   - ipython
   - mpmath
   - pip:
     - git+https://github.com/birnstiel/dsharp_opac.git