name: base
channels:
dependencies:
   - setuptools
   - numpy
   - numba
   - scipy
   - matplotlib
   - astropy
   - ipython
   - mpmath
   - pip:
     - "--editable=git+https://github.com/birnstiel/dsharp_opac.git#egg=dsharp_opac-master"
